package com.tuarua.facebook {
public class SharePhoto {
    private var _imageUrl:String;
    private var _isUserGenerated:Boolean;

    public function SharePhoto() {
    }

    /** The URL to the photo.*/
    public function get imageUrl():String {
        return _imageUrl;
    }

    public function set imageUrl(value:String):void {
        _imageUrl = value;
    }

    /** Specifies whether the photo represented by the receiver was generated by the user or by the application. */
    public function get isUserGenerated():Boolean {
        return _isUserGenerated;
    }

    public function set isUserGenerated(value:Boolean):void {
        _isUserGenerated = value;
    }
}
}
